# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: crawler.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcrawler.proto\x12\x0e\x63rawlerProcess\"\x1d\n\x0e\x43RAWLERRequest\x12\x0b\n\x03url\x18\x01 \x01(\t\"\x1c\n\x0c\x43RAWLERReply\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t2\xb3\x01\n\x0e\x63rawlerProcess\x12I\n\x07\x63rawler\x12\x1e.crawlerProcess.CRAWLERRequest\x1a\x1c.crawlerProcess.CRAWLERReply\"\x00\x12V\n\x12\x63rawlerStreamReply\x12\x1e.crawlerProcess.CRAWLERRequest\x1a\x1c.crawlerProcess.CRAWLERReply\"\x00\x30\x01\x42\x36\n\x1bio.grpc.examples.helloworldB\x0fHelloWorldProtoP\x01\xa2\x02\x03HLWb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'crawler_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033io.grpc.examples.helloworldB\017HelloWorldProtoP\001\242\002\003HLW'
  _globals['_CRAWLERREQUEST']._serialized_start=33
  _globals['_CRAWLERREQUEST']._serialized_end=62
  _globals['_CRAWLERREPLY']._serialized_start=64
  _globals['_CRAWLERREPLY']._serialized_end=92
  _globals['_CRAWLERPROCESS']._serialized_start=95
  _globals['_CRAWLERPROCESS']._serialized_end=274
# @@protoc_insertion_point(module_scope)
